# -*- coding: utf-8 -*-
"""Final_Classification_Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bxgWbdrirIRSbfxLO4QP-_Yl99SkK0L
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
import os
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

# loading dataset
dataset = pd.read_csv(sys.argv[1])

# data cleaning and feature engineering
drop_col = ['First Name', 'Last Name', 'State', 'Zip Code', 'DOB [DD/MM/YYYY]', 'Age', 'Gender', 'Email Address', 'Contact Number', 'Emergency Contact Number', 'University Name', 'Degree', 'Course Type', 'Current Employment Status', 'Certifications/Achievement/ Research papers', 'Link to updated Resume (Google/ One Drive link preferred)', 'link to Linkedin profile']

dataset.drop(drop_col, inplace=True, axis = 1)

# encoding categorical variables
dataset['En_Label'] = LabelEncoder().fit_transform(dataset['Label'])
dataset['En_Year'] = LabelEncoder().fit_transform(dataset['Which-year are you studying in?'])
dataset['En_CGPA'] = LabelEncoder().fit_transform(dataset['CGPA/ percentage'])
dataset['En_Major'] = LabelEncoder().fit_transform(dataset['Major/Area of Study'])
dataset['En_Prog_Languages'] = LabelEncoder().fit_transform(dataset['Programming Language Known other than Java (one major)'])
dataset['En_Interest'] = LabelEncoder().fit_transform(dataset['Areas of interest'])
dataset['En_written_score'] = LabelEncoder().fit_transform(dataset['Rate your written communication skills [1-10]'])
dataset['En_verbal_score'] = LabelEncoder().fit_transform(dataset['Rate your verbal communication skills [1-10]'])
dataset['En_SQL'] = LabelEncoder().fit_transform(dataset['Have you worked on MySQL or Oracle database'])
dataset['En_Java'] = LabelEncoder().fit_transform(dataset['Have you worked core Java'])
dataset['En_OOP'] = dataset['Have you studied OOP Concepts'].map({'Yes':1, 'No':0})

features = ['En_Year','En_CGPA','En_Major','En_Prog_Languages','En_Interest','En_written_score' ,'En_verbal_score','En_SQL','En_Java','En_OOP']
X = dataset[features] 
y = dataset['En_Label'] 


#train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Random Forest Model
model=RandomForestClassifier(n_estimators=1)

# fitting dataset to model
model.fit(X_train,y_train)

y_pred=model.predict(X_test)

# Accuracy Metrics
from sklearn import metrics
print(metrics.f1_score(y_test, y_pred))

